# Generated by Django 5.0.7 on 2024-08-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathroom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedroom',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='living_area',
            field=models.IntegerField(),
        ),
    ]
