# Generated by Django 5.0.7 on 2024-08-03 11:49

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSingleCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blogger_name', models.CharField(max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
