# Generated by Django 5.0.7 on 2024-08-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_contact_delete_contactquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
