# Generated by Django 5.0.7 on 2024-08-07 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsinglecreative',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.blog'),
        ),
    ]
