# Generated by Django 5.0.7 on 2024-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_agents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
